### ISSUE TITLE
有遇到下载出这种错吗？百度的解决办法还是报错...

### ISSUE THREAD

**Issue by wwwqqq566** [sknightq/vue-mpc#1]
Downloading https://chromedriver.storage.googleapis.com/2.37/chromedriver_mac64.zip
Saving to /var/folders/7x/4lpj7n6n4zd7fc6r1xc4_7cc0000gr/T/chromedriver/chromedriver_mac64.zip
ChromeDriver installation failed Error with http(s) request: Error: connect ETIMEDOUT 43.245.195.27:443
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@2.37.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.37.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qq/.npm/_logs/2018-05-24T07_00_03_465Z-debug.log
rj-2:test-mulit-vue qq$ npm install cross-env --save-dev

> chromedriver@2.37.0 install /Users/qq/Desktop/test-mulit-vue/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.37/chromedriver_mac64.zip
Saving to /var/folders/7x/4lpj7n6n4zd7fc6r1xc4_7cc0000gr/T/chromedriver/chromedriver_mac64.zip
ChromeDriver installation failed Error with http(s) request: Error: connect ETIMEDOUT 43.245.195.27:443
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@2.37.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.37.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qq/.npm/_logs/2018-05-24T07_06_10_986Z-debug.log

**Comment by sknightq** [comment]
你是用什么源的？建议更改下镜像源试试，我WIN和MAC上都初始化这个项目，没报错
